#!/bin/bash

# Comprehensive Test Suite for Pricing and Promotions Service API v2.0
# Tests all 12 Active/Core business rules and every contract operation.
# Generated by SAAM Phase 4c. ZERO SKIPS.

set -u
BASE_URL="${BASE_URL:-http://localhost:8107/api/v1}"
PASSED=0
FAILED=0
TOTAL=0
GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'
declare -a FAILED_TESTS=()
RESOURCE_ID='00000000-0000-0000-0000-000000000001'
LAST_STATUS=''
LAST_BODY=''

# Global headers from x-global-headers in 04-api-contract.yaml.
XTENANTID_HEADER="x-tenant-id: 2e6d7b63-5b1d-4f8a-8e12-8cf43c9f2001"
XSTOREID_HEADER="x-store-id: store-us-east"
XCORRELATIONID_HEADER="x-correlation-id: corr-20260901-000184"
GLOBAL_HEADERS=("${XTENANTID_HEADER}" "${XSTOREID_HEADER}" "${XCORRELATIONID_HEADER}")

extract_field() {
    local json=$1
    local field=$2
    if command -v jq >/dev/null 2>&1; then
        printf '%s' "$json" | jq -r --arg field "$field" '.[$field] // empty'
    else
        python3 -c 'import json,sys; d=json.load(sys.stdin); print(d.get(sys.argv[1], ""))' "$field" <<<"$json"
    fi
}

request() {
    local method=$1 url=$2 payload=$3
    local response
    if [ "$payload" = "null" ]; then
        response=$(curl -sS -w '\n%{http_code}' -X "$method" "$url" "${GLOBAL_HEADERS[@]}")
    else
        response=$(curl -sS -w '\n%{http_code}' -X "$method" "$url" "${GLOBAL_HEADERS[@]}" -H 'Content-Type: application/json' -d "$payload")
    fi
    LAST_STATUS=$(printf '%s\n' "$response" | tail -n 1)
    LAST_BODY=$(printf '%s\n' "$response" | sed '$d')
}

assert_case() {
    local test_num=$1 name=$2 rule_id=$3 method=$4 url=$5 payload=$6 expected=$7 field=${8:-}
    TOTAL=$((TOTAL + 1))
    echo -e "\n${BLUE}Test $test_num: $name${NC}"
    echo "  Rule: $rule_id | $method $url | Expected: $expected"
    request "$method" "$url" "$payload"
    if [ "$LAST_STATUS" = "$expected" ]; then
        if [ -n "$field" ] && [ "$expected" != "204" ]; then
            local value
            value=$(extract_field "$LAST_BODY" "$field")
            if [ -z "$value" ]; then
                echo -e "  ${RED}FAILED${NC}: response field '$field' is missing"
                FAILED=$((FAILED + 1))
                FAILED_TESTS+=("Test $test_num: $name [$rule_id] missing $field")
                return 1
            fi
        fi
        for candidate in id subjectId customerId productId orderId paymentIntentId storeId; do
            local candidate_value
            candidate_value=$(extract_field "$LAST_BODY" "$candidate")
            if [ -n "$candidate_value" ] && [ "$candidate_value" != "null" ]; then
                RESOURCE_ID="$candidate_value"
                break
            fi
        done
        echo -e "  ${GREEN}PASSED${NC} (HTTP $LAST_STATUS)"
        PASSED=$((PASSED + 1))
        return 0
    fi
    echo -e "  ${RED}FAILED${NC} (Expected $expected, got $LAST_STATUS)"
    FAILED=$((FAILED + 1))
    FAILED_TESTS+=("Test $test_num: $name [$rule_id] expected $expected got $LAST_STATUS")
    return 1
}

assert_status() { assert_case "$@"; }
assert_json_field() {
    local test_num=$1 name=$2 rule_id=$3 method=$4 url=$5 payload=$6 field=$7 expected=${8:-200}
    assert_case "$test_num" "$name" "$rule_id" "$method" "$url" "$payload" "$expected" "$field"
}
assert_json_regex() {
    local test_num=$1 name=$2 rule_id=$3 method=$4 url=$5 payload=$6 regex=$7
    TOTAL=$((TOTAL + 1))
    request "$method" "$url" "$payload"
    if printf '%s' "$LAST_BODY" | grep -qE "$regex"; then
        PASSED=$((PASSED + 1))
        return 0
    fi
    FAILED=$((FAILED + 1))
    FAILED_TESTS+=("Test $test_num: $name [$rule_id] regex did not match")
    return 1
}

echo '=============================================='
echo 'Pricing and Promotions Service API - Comprehensive Test Suite v2.0'
echo 'Active/Core business rules: 12 | Contract operations: 13'
echo '=============================================='
if ! curl -sS -f "$BASE_URL/health" >/dev/null 2>&1; then
    echo -e "${YELLOW}Service health endpoint is not available; continuing with contract probes.${NC}"
fi

assert_json_field 1 "Contract success: POST /pricing/products/{sku}/quote" BR-PRC-001 POST "$BASE_URL/pricing/products/phase4c-sku/quote" "{\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"attributes\":[{\"attributeId\":\"00000000-0000-0000-0000-000000000001\",\"valueId\":\"00000000-0000-0000-0000-000000000001\",\"priceAdjustment\":10.5}],\"evaluationAt\":\"2026-09-02T00:00:00Z\"}" "productSku" 200 || true
assert_status 2 "Contract error/conformance: POST /pricing/products/{sku}/quote" BR-PRC-001 POST "$BASE_URL/pricing/products/phase4c-sku/quote" "{}" 400 || true
assert_json_field 3 "Business rule assertion: BR-PRC-001" BR-PRC-001 POST "$BASE_URL/pricing/products/phase4c-sku/quote" "{\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"attributes\":[{\"attributeId\":\"00000000-0000-0000-0000-000000000001\",\"valueId\":\"00000000-0000-0000-0000-000000000001\",\"priceAdjustment\":10.5}],\"evaluationAt\":\"2026-09-02T00:00:00Z\"}" "productSku" 200 || true
assert_json_field 4 "Business rule assertion: BR-PRC-002" BR-PRC-002 POST "$BASE_URL/pricing/products/phase4c-sku/quote" "{\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"attributes\":[{\"attributeId\":\"00000000-0000-0000-0000-000000000001\",\"valueId\":\"00000000-0000-0000-0000-000000000001\",\"priceAdjustment\":10.5}],\"evaluationAt\":\"2026-09-02T00:00:00Z\"}" "productSku" 200 || true
assert_json_field 5 "Business rule assertion: BR-PRC-003" BR-PRC-003 POST "$BASE_URL/pricing/products/phase4c-sku/quote" "{\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"attributes\":[{\"attributeId\":\"00000000-0000-0000-0000-000000000001\",\"valueId\":\"00000000-0000-0000-0000-000000000001\",\"priceAdjustment\":10.5}],\"evaluationAt\":\"2026-09-02T00:00:00Z\"}" "productSku" 200 || true
assert_json_field 6 "Business rule assertion: BR-PRC-004" BR-PRC-004 POST "$BASE_URL/pricing/products/phase4c-sku/quote" "{\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"attributes\":[{\"attributeId\":\"00000000-0000-0000-0000-000000000001\",\"valueId\":\"00000000-0000-0000-0000-000000000001\",\"priceAdjustment\":10.5}],\"evaluationAt\":\"2026-09-02T00:00:00Z\"}" "productSku" 200 || true
assert_json_field 7 "Business rule assertion: BR-PRC-005" BR-PRC-005 POST "$BASE_URL/pricing/products/phase4c-sku/quote" "{\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"attributes\":[{\"attributeId\":\"00000000-0000-0000-0000-000000000001\",\"valueId\":\"00000000-0000-0000-0000-000000000001\",\"priceAdjustment\":10.5}],\"evaluationAt\":\"2026-09-02T00:00:00Z\"}" "productSku" 200 || true
assert_json_field 8 "Business rule assertion: BR-PRC-006" BR-PRC-006 POST "$BASE_URL/pricing/products/phase4c-sku/quote" "{\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"attributes\":[{\"attributeId\":\"00000000-0000-0000-0000-000000000001\",\"valueId\":\"00000000-0000-0000-0000-000000000001\",\"priceAdjustment\":10.5}],\"evaluationAt\":\"2026-09-02T00:00:00Z\"}" "productSku" 200 || true
assert_json_field 9 "Business rule assertion: BR-PRC-007" BR-PRC-007 POST "$BASE_URL/pricing/products/phase4c-sku/quote" "{\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"attributes\":[{\"attributeId\":\"00000000-0000-0000-0000-000000000001\",\"valueId\":\"00000000-0000-0000-0000-000000000001\",\"priceAdjustment\":10.5}],\"evaluationAt\":\"2026-09-02T00:00:00Z\"}" "productSku" 200 || true
assert_json_field 10 "Business rule assertion: BR-PRC-008" BR-PRC-008 POST "$BASE_URL/pricing/products/phase4c-sku/quote" "{\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"attributes\":[{\"attributeId\":\"00000000-0000-0000-0000-000000000001\",\"valueId\":\"00000000-0000-0000-0000-000000000001\",\"priceAdjustment\":10.5}],\"evaluationAt\":\"2026-09-02T00:00:00Z\"}" "productSku" 200 || true
assert_json_field 11 "Business rule assertion: BR-PRC-009" BR-PRC-009 POST "$BASE_URL/pricing/products/phase4c-sku/quote" "{\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"attributes\":[{\"attributeId\":\"00000000-0000-0000-0000-000000000001\",\"valueId\":\"00000000-0000-0000-0000-000000000001\",\"priceAdjustment\":10.5}],\"evaluationAt\":\"2026-09-02T00:00:00Z\"}" "productSku" 200 || true
assert_json_field 12 "Business rule assertion: BR-PRC-011" BR-PRC-011 POST "$BASE_URL/pricing/products/phase4c-sku/quote" "{\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"attributes\":[{\"attributeId\":\"00000000-0000-0000-0000-000000000001\",\"valueId\":\"00000000-0000-0000-0000-000000000001\",\"priceAdjustment\":10.5}],\"evaluationAt\":\"2026-09-02T00:00:00Z\"}" "productSku" 200 || true
assert_json_field 13 "Business rule assertion: BR-PRC-012" BR-PRC-012 POST "$BASE_URL/pricing/products/phase4c-sku/quote" "{\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"attributes\":[{\"attributeId\":\"00000000-0000-0000-0000-000000000001\",\"valueId\":\"00000000-0000-0000-0000-000000000001\",\"priceAdjustment\":10.5}],\"evaluationAt\":\"2026-09-02T00:00:00Z\"}" "productSku" 200 || true
assert_json_field 14 "Business rule assertion: BR-PRC-013" BR-PRC-013 POST "$BASE_URL/pricing/products/phase4c-sku/quote" "{\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"attributes\":[{\"attributeId\":\"00000000-0000-0000-0000-000000000001\",\"valueId\":\"00000000-0000-0000-0000-000000000001\",\"priceAdjustment\":10.5}],\"evaluationAt\":\"2026-09-02T00:00:00Z\"}" "productSku" 200 || true
assert_json_field 15 "Contract success: POST /pricing/promotions/evaluate" BR-PRC-001 POST "$BASE_URL/pricing/promotions/evaluate" "{\"promoCode\":\"phase4c-test\",\"items\":[{\"productSku\":\"phase4c-test\",\"variantSku\":\"phase4c-test\",\"quantity\":1,\"attributes\":[{\"attributeId\":\"00000000-0000-0000-0000-000000000001\",\"valueId\":\"00000000-0000-0000-0000-000000000001\",\"priceAdjustment\":10.5}]}],\"evaluationAt\":\"2026-09-02T00:00:00Z\"}" "items" 200 || true
assert_status 16 "Contract error/conformance: POST /pricing/promotions/evaluate" BR-PRC-001 POST "$BASE_URL/pricing/promotions/evaluate" "{}" 400 || true
assert_json_field 17 "Contract success: POST /pricing/quotes" BR-PRC-001 POST "$BASE_URL/pricing/quotes" "{\"currency\":\"phase4c-test\",\"items\":[{\"productSku\":\"phase4c-test\",\"variantSku\":\"phase4c-test\",\"quantity\":1,\"attributes\":[{\"attributeId\":\"00000000-0000-0000-0000-000000000001\",\"valueId\":\"00000000-0000-0000-0000-000000000001\",\"priceAdjustment\":10.5}]}],\"promoCode\":\"phase4c-test\",\"evaluationAt\":\"2026-09-02T00:00:00Z\"}" "items" 200 || true
assert_status 18 "Contract error/conformance: POST /pricing/quotes" BR-PRC-001 POST "$BASE_URL/pricing/quotes" "{}" 400 || true
assert_json_field 19 "Contract success: POST /pricing/variants/{variantSku}/quote" BR-PRC-001 POST "$BASE_URL/pricing/variants/phase4c-sku/quote" "{\"parentProductSku\":\"phase4c-test\",\"fallbackMode\":\"DirectOnly\",\"evaluationAt\":\"2026-09-02T00:00:00Z\"}" "productSku" 200 || true
assert_status 20 "Contract error/conformance: POST /pricing/variants/{variantSku}/quote" BR-PRC-001 POST "$BASE_URL/pricing/variants/phase4c-sku/quote" "{}" 400 || true
assert_json_field 21 "Contract success: POST /private/products/{sku}/availabilities/{availabilityId}/prices" BR-PRC-001 POST "$BASE_URL/private/products/phase4c-sku/availabilities/${RESOURCE_ID}/prices" "{\"code\":\"phase4c-test\",\"amount\":10.5,\"priceType\":\"OneTime\",\"defaultPrice\":true,\"specialStartDate\":\"2026-09-02\",\"specialEndDate\":\"2026-09-02\",\"specialAmount\":10.5,\"productIdentifierId\":1}" "id" 201 || true
assert_status 22 "Contract error/conformance: POST /private/products/{sku}/availabilities/{availabilityId}/prices" BR-PRC-001 POST "$BASE_URL/private/products/phase4c-sku/availabilities/${RESOURCE_ID}/prices" "{}" 400 || true
assert_json_field 23 "Contract success: POST /private/products/{sku}/prices" BR-PRC-001 POST "$BASE_URL/private/products/phase4c-sku/prices" "{\"availabilityId\":1,\"code\":\"phase4c-test\",\"amount\":10.5,\"priceType\":\"OneTime\",\"defaultPrice\":true,\"specialStartDate\":\"2026-09-02\",\"specialEndDate\":\"2026-09-02\",\"specialAmount\":10.5,\"productIdentifierId\":1}" "id" 201 || true
assert_status 24 "Contract error/conformance: POST /private/products/{sku}/prices" BR-PRC-001 POST "$BASE_URL/private/products/phase4c-sku/prices" "{}" 400 || true
assert_json_field 25 "Contract success: GET /pricing/products/{sku}/price" BR-PRC-001 GET "$BASE_URL/pricing/products/phase4c-sku/price" "null" "productSku" 200 || true
assert_status 26 "Contract error/conformance: GET /pricing/products/{sku}/price" BR-PRC-001 GET "$BASE_URL/pricing/products/phase4c-sku/price" "null" 400 || true
assert_json_field 27 "Contract success: GET /private/pricing/processors" BR-PRC-001 GET "$BASE_URL/private/pricing/processors" "null" "processors" 200 || true
assert_status 28 "Contract error/conformance: GET /private/pricing/processors" BR-PRC-001 GET "$BASE_URL/private/pricing/processors" "null" 401 || true
assert_json_field 29 "Contract success: GET /private/products/{sku}/availabilities/{availabilityId}/prices" BR-PRC-001 GET "$BASE_URL/private/products/phase4c-sku/availabilities/${RESOURCE_ID}/prices" "null" "items" 200 || true
assert_status 30 "Contract error/conformance: GET /private/products/{sku}/availabilities/{availabilityId}/prices" BR-PRC-001 GET "$BASE_URL/private/products/phase4c-sku/availabilities/${RESOURCE_ID}/prices" "null" 400 || true
assert_json_field 31 "Contract success: GET /private/products/{sku}/prices" BR-PRC-001 GET "$BASE_URL/private/products/phase4c-sku/prices" "null" "items" 200 || true
assert_status 32 "Contract error/conformance: GET /private/products/{sku}/prices" BR-PRC-001 GET "$BASE_URL/private/products/phase4c-sku/prices" "null" 400 || true
assert_json_field 33 "Contract success: GET /private/products/{sku}/prices/{priceId}" BR-PRC-001 GET "$BASE_URL/private/products/phase4c-sku/prices/${RESOURCE_ID}" "null" "id" 200 || true
assert_status 34 "Contract error/conformance: GET /private/products/{sku}/prices/{priceId}" BR-PRC-001 GET "$BASE_URL/private/products/phase4c-sku/prices/${RESOURCE_ID}" "null" 400 || true
assert_json_field 35 "Contract success: PUT /private/products/{sku}/availabilities/{availabilityId}/prices/{priceId}" BR-PRC-001 PUT "$BASE_URL/private/products/phase4c-sku/availabilities/${RESOURCE_ID}/prices/${RESOURCE_ID}" "{\"code\":\"phase4c-test\",\"amount\":10.5,\"priceType\":\"OneTime\",\"defaultPrice\":true,\"specialStartDate\":\"2026-09-02\",\"specialEndDate\":\"2026-09-02\",\"specialAmount\":10.5,\"productIdentifierId\":1}" "id" 200 || true
assert_status 36 "Contract error/conformance: PUT /private/products/{sku}/availabilities/{availabilityId}/prices/{priceId}" BR-PRC-001 PUT "$BASE_URL/private/products/phase4c-sku/availabilities/${RESOURCE_ID}/prices/${RESOURCE_ID}" "{}" 400 || true
assert_json_field 37 "Contract success: DELETE /private/products/{sku}/prices/{priceId}" BR-PRC-001 DELETE "$BASE_URL/private/products/phase4c-sku/prices/${RESOURCE_ID}" "null" "id" 204 || true
assert_status 38 "Contract error/conformance: DELETE /private/products/{sku}/prices/{priceId}" BR-PRC-001 DELETE "$BASE_URL/private/products/phase4c-sku/prices/${RESOURCE_ID}" "null" 400 || true

echo -e "\n=============================================="
echo "Results: $PASSED passed, $FAILED failed, $TOTAL total"
if [ "$FAILED" -eq 0 ]; then
    echo "ALL  + str(test_num - 1) +  TESTS PASSED - 100% SUCCESS"
    exit 0
fi
echo "TEST SUITE FAILED"
printf '%s\n' "${FAILED_TESTS[@]}"
exit 1
