#!/bin/bash

# Comprehensive Test Suite for MS-08 Tax API v2.0
# Tests all 20 Active/Core business rules and every contract operation.
# Generated by SAAM Phase 4c. ZERO SKIPS.

set -u
BASE_URL="${BASE_URL:-http://localhost:8108/api/v1}"
PASSED=0
FAILED=0
TOTAL=0
GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'
declare -a FAILED_TESTS=()
RESOURCE_ID='00000000-0000-0000-0000-000000000001'
LAST_STATUS=''
LAST_BODY=''

# Global headers from x-global-headers in 04-api-contract.yaml.
XTENANTID_HEADER="x-tenant-id: tenant-001"
XSTOREID_HEADER="x-store-id: store-001"
XCORRELATIONID_HEADER="x-correlation-id: corr-001"
AUTHORIZATION_HEADER="Authorization: Bearer phase4c-test-token"
GLOBAL_HEADERS=("${XTENANTID_HEADER}" "${XSTOREID_HEADER}" "${XCORRELATIONID_HEADER}" "${AUTHORIZATION_HEADER}")

extract_field() {
    local json=$1
    local field=$2
    if command -v jq >/dev/null 2>&1; then
        printf '%s' "$json" | jq -r --arg field "$field" '.[$field] // empty'
    else
        python3 -c 'import json,sys; d=json.load(sys.stdin); print(d.get(sys.argv[1], ""))' "$field" <<<"$json"
    fi
}

request() {
    local method=$1 url=$2 payload=$3
    local response
    if [ "$payload" = "null" ]; then
        response=$(curl -sS -w '\n%{http_code}' -X "$method" "$url" "${GLOBAL_HEADERS[@]}")
    else
        response=$(curl -sS -w '\n%{http_code}' -X "$method" "$url" "${GLOBAL_HEADERS[@]}" -H 'Content-Type: application/json' -d "$payload")
    fi
    LAST_STATUS=$(printf '%s\n' "$response" | tail -n 1)
    LAST_BODY=$(printf '%s\n' "$response" | sed '$d')
}

assert_case() {
    local test_num=$1 name=$2 rule_id=$3 method=$4 url=$5 payload=$6 expected=$7 field=${8:-}
    TOTAL=$((TOTAL + 1))
    echo -e "\n${BLUE}Test $test_num: $name${NC}"
    echo "  Rule: $rule_id | $method $url | Expected: $expected"
    request "$method" "$url" "$payload"
    if [ "$LAST_STATUS" = "$expected" ]; then
        if [ -n "$field" ] && [ "$expected" != "204" ]; then
            local value
            value=$(extract_field "$LAST_BODY" "$field")
            if [ -z "$value" ]; then
                echo -e "  ${RED}FAILED${NC}: response field '$field' is missing"
                FAILED=$((FAILED + 1))
                FAILED_TESTS+=("Test $test_num: $name [$rule_id] missing $field")
                return 1
            fi
        fi
        for candidate in id subjectId customerId productId orderId paymentIntentId storeId; do
            local candidate_value
            candidate_value=$(extract_field "$LAST_BODY" "$candidate")
            if [ -n "$candidate_value" ] && [ "$candidate_value" != "null" ]; then
                RESOURCE_ID="$candidate_value"
                break
            fi
        done
        echo -e "  ${GREEN}PASSED${NC} (HTTP $LAST_STATUS)"
        PASSED=$((PASSED + 1))
        return 0
    fi
    echo -e "  ${RED}FAILED${NC} (Expected $expected, got $LAST_STATUS)"
    FAILED=$((FAILED + 1))
    FAILED_TESTS+=("Test $test_num: $name [$rule_id] expected $expected got $LAST_STATUS")
    return 1
}

assert_status() { assert_case "$@"; }
assert_json_field() {
    local test_num=$1 name=$2 rule_id=$3 method=$4 url=$5 payload=$6 field=$7 expected=${8:-200}
    assert_case "$test_num" "$name" "$rule_id" "$method" "$url" "$payload" "$expected" "$field"
}
assert_json_regex() {
    local test_num=$1 name=$2 rule_id=$3 method=$4 url=$5 payload=$6 regex=$7
    TOTAL=$((TOTAL + 1))
    request "$method" "$url" "$payload"
    if printf '%s' "$LAST_BODY" | grep -qE "$regex"; then
        PASSED=$((PASSED + 1))
        return 0
    fi
    FAILED=$((FAILED + 1))
    FAILED_TESTS+=("Test $test_num: $name [$rule_id] regex did not match")
    return 1
}

echo '=============================================='
echo 'MS-08 Tax API - Comprehensive Test Suite v2.0'
echo 'Active/Core business rules: 20 | Contract operations: 15'
echo '=============================================='
if ! curl -sS -f "$BASE_URL/health" >/dev/null 2>&1; then
    echo -e "${YELLOW}Service health endpoint is not available; continuing with contract probes.${NC}"
fi

assert_json_field 1 "Contract success: POST /tax-calculations" BR-TAX-CFG-001 POST "$BASE_URL/tax-calculations" "{\"currencyCode\":\"phase4c-test\",\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"orderId\":\"00000000-0000-0000-0000-000000000001\",\"billingAddress\":{\"countryCode\":\"phase4c-test\",\"zoneCode\":\"phase4c-test\",\"stateProvince\":\"phase4c-test\"},\"shippingAddress\":\"phase4c-test\",\"items\":[{\"productId\":\"00000000-0000-0000-0000-000000000001\",\"quantity\":1,\"unitAmount\":10.5,\"taxClassCode\":\"phase4c-test\"}],\"shipping\":\"phase4c-test\",\"languageCode\":\"phase4c-test\",\"idempotencyKey\":\"phase4c-test\"}" "quoteId" 200 || true
assert_status 2 "Contract error/conformance: POST /tax-calculations" BR-TAX-CFG-001 POST "$BASE_URL/tax-calculations" "{}" 400 || true
assert_json_field 3 "Business rule assertion: BR-TAX-CFG-001" BR-TAX-CFG-001 POST "$BASE_URL/tax-calculations" "{\"currencyCode\":\"phase4c-test\",\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"orderId\":\"00000000-0000-0000-0000-000000000001\",\"billingAddress\":{\"countryCode\":\"phase4c-test\",\"zoneCode\":\"phase4c-test\",\"stateProvince\":\"phase4c-test\"},\"shippingAddress\":\"phase4c-test\",\"items\":[{\"productId\":\"00000000-0000-0000-0000-000000000001\",\"quantity\":1,\"unitAmount\":10.5,\"taxClassCode\":\"phase4c-test\"}],\"shipping\":\"phase4c-test\",\"languageCode\":\"phase4c-test\",\"idempotencyKey\":\"phase4c-test\"}" "quoteId" 200 || true
assert_json_field 4 "Business rule assertion: BR-TAX-CFG-002" BR-TAX-CFG-002 POST "$BASE_URL/tax-calculations" "{\"currencyCode\":\"phase4c-test\",\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"orderId\":\"00000000-0000-0000-0000-000000000001\",\"billingAddress\":{\"countryCode\":\"phase4c-test\",\"zoneCode\":\"phase4c-test\",\"stateProvince\":\"phase4c-test\"},\"shippingAddress\":\"phase4c-test\",\"items\":[{\"productId\":\"00000000-0000-0000-0000-000000000001\",\"quantity\":1,\"unitAmount\":10.5,\"taxClassCode\":\"phase4c-test\"}],\"shipping\":\"phase4c-test\",\"languageCode\":\"phase4c-test\",\"idempotencyKey\":\"phase4c-test\"}" "quoteId" 200 || true
assert_json_field 5 "Business rule assertion: BR-TAX-CLS-001" BR-TAX-CLS-001 POST "$BASE_URL/tax-calculations" "{\"currencyCode\":\"phase4c-test\",\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"orderId\":\"00000000-0000-0000-0000-000000000001\",\"billingAddress\":{\"countryCode\":\"phase4c-test\",\"zoneCode\":\"phase4c-test\",\"stateProvince\":\"phase4c-test\"},\"shippingAddress\":\"phase4c-test\",\"items\":[{\"productId\":\"00000000-0000-0000-0000-000000000001\",\"quantity\":1,\"unitAmount\":10.5,\"taxClassCode\":\"phase4c-test\"}],\"shipping\":\"phase4c-test\",\"languageCode\":\"phase4c-test\",\"idempotencyKey\":\"phase4c-test\"}" "quoteId" 200 || true
assert_json_field 6 "Business rule assertion: BR-TAX-CLS-002" BR-TAX-CLS-002 POST "$BASE_URL/tax-calculations" "{\"currencyCode\":\"phase4c-test\",\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"orderId\":\"00000000-0000-0000-0000-000000000001\",\"billingAddress\":{\"countryCode\":\"phase4c-test\",\"zoneCode\":\"phase4c-test\",\"stateProvince\":\"phase4c-test\"},\"shippingAddress\":\"phase4c-test\",\"items\":[{\"productId\":\"00000000-0000-0000-0000-000000000001\",\"quantity\":1,\"unitAmount\":10.5,\"taxClassCode\":\"phase4c-test\"}],\"shipping\":\"phase4c-test\",\"languageCode\":\"phase4c-test\",\"idempotencyKey\":\"phase4c-test\"}" "quoteId" 200 || true
assert_json_field 7 "Business rule assertion: BR-TAX-CLS-003" BR-TAX-CLS-003 POST "$BASE_URL/tax-calculations" "{\"currencyCode\":\"phase4c-test\",\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"orderId\":\"00000000-0000-0000-0000-000000000001\",\"billingAddress\":{\"countryCode\":\"phase4c-test\",\"zoneCode\":\"phase4c-test\",\"stateProvince\":\"phase4c-test\"},\"shippingAddress\":\"phase4c-test\",\"items\":[{\"productId\":\"00000000-0000-0000-0000-000000000001\",\"quantity\":1,\"unitAmount\":10.5,\"taxClassCode\":\"phase4c-test\"}],\"shipping\":\"phase4c-test\",\"languageCode\":\"phase4c-test\",\"idempotencyKey\":\"phase4c-test\"}" "quoteId" 200 || true
assert_json_field 8 "Business rule assertion: BR-TAX-RAT-001" BR-TAX-RAT-001 POST "$BASE_URL/tax-calculations" "{\"currencyCode\":\"phase4c-test\",\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"orderId\":\"00000000-0000-0000-0000-000000000001\",\"billingAddress\":{\"countryCode\":\"phase4c-test\",\"zoneCode\":\"phase4c-test\",\"stateProvince\":\"phase4c-test\"},\"shippingAddress\":\"phase4c-test\",\"items\":[{\"productId\":\"00000000-0000-0000-0000-000000000001\",\"quantity\":1,\"unitAmount\":10.5,\"taxClassCode\":\"phase4c-test\"}],\"shipping\":\"phase4c-test\",\"languageCode\":\"phase4c-test\",\"idempotencyKey\":\"phase4c-test\"}" "quoteId" 200 || true
assert_json_field 9 "Business rule assertion: BR-TAX-RAT-002" BR-TAX-RAT-002 POST "$BASE_URL/tax-calculations" "{\"currencyCode\":\"phase4c-test\",\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"orderId\":\"00000000-0000-0000-0000-000000000001\",\"billingAddress\":{\"countryCode\":\"phase4c-test\",\"zoneCode\":\"phase4c-test\",\"stateProvince\":\"phase4c-test\"},\"shippingAddress\":\"phase4c-test\",\"items\":[{\"productId\":\"00000000-0000-0000-0000-000000000001\",\"quantity\":1,\"unitAmount\":10.5,\"taxClassCode\":\"phase4c-test\"}],\"shipping\":\"phase4c-test\",\"languageCode\":\"phase4c-test\",\"idempotencyKey\":\"phase4c-test\"}" "quoteId" 200 || true
assert_json_field 10 "Business rule assertion: BR-TAX-RAT-003" BR-TAX-RAT-003 POST "$BASE_URL/tax-calculations" "{\"currencyCode\":\"phase4c-test\",\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"orderId\":\"00000000-0000-0000-0000-000000000001\",\"billingAddress\":{\"countryCode\":\"phase4c-test\",\"zoneCode\":\"phase4c-test\",\"stateProvince\":\"phase4c-test\"},\"shippingAddress\":\"phase4c-test\",\"items\":[{\"productId\":\"00000000-0000-0000-0000-000000000001\",\"quantity\":1,\"unitAmount\":10.5,\"taxClassCode\":\"phase4c-test\"}],\"shipping\":\"phase4c-test\",\"languageCode\":\"phase4c-test\",\"idempotencyKey\":\"phase4c-test\"}" "quoteId" 200 || true
assert_json_field 11 "Business rule assertion: BR-TAX-RAT-004" BR-TAX-RAT-004 POST "$BASE_URL/tax-calculations" "{\"currencyCode\":\"phase4c-test\",\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"orderId\":\"00000000-0000-0000-0000-000000000001\",\"billingAddress\":{\"countryCode\":\"phase4c-test\",\"zoneCode\":\"phase4c-test\",\"stateProvince\":\"phase4c-test\"},\"shippingAddress\":\"phase4c-test\",\"items\":[{\"productId\":\"00000000-0000-0000-0000-000000000001\",\"quantity\":1,\"unitAmount\":10.5,\"taxClassCode\":\"phase4c-test\"}],\"shipping\":\"phase4c-test\",\"languageCode\":\"phase4c-test\",\"idempotencyKey\":\"phase4c-test\"}" "quoteId" 200 || true
assert_json_field 12 "Business rule assertion: BR-TAX-RAT-005" BR-TAX-RAT-005 POST "$BASE_URL/tax-calculations" "{\"currencyCode\":\"phase4c-test\",\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"orderId\":\"00000000-0000-0000-0000-000000000001\",\"billingAddress\":{\"countryCode\":\"phase4c-test\",\"zoneCode\":\"phase4c-test\",\"stateProvince\":\"phase4c-test\"},\"shippingAddress\":\"phase4c-test\",\"items\":[{\"productId\":\"00000000-0000-0000-0000-000000000001\",\"quantity\":1,\"unitAmount\":10.5,\"taxClassCode\":\"phase4c-test\"}],\"shipping\":\"phase4c-test\",\"languageCode\":\"phase4c-test\",\"idempotencyKey\":\"phase4c-test\"}" "quoteId" 200 || true
assert_json_field 13 "Business rule assertion: BR-TAX-CAL-001" BR-TAX-CAL-001 POST "$BASE_URL/tax-calculations" "{\"currencyCode\":\"phase4c-test\",\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"orderId\":\"00000000-0000-0000-0000-000000000001\",\"billingAddress\":{\"countryCode\":\"phase4c-test\",\"zoneCode\":\"phase4c-test\",\"stateProvince\":\"phase4c-test\"},\"shippingAddress\":\"phase4c-test\",\"items\":[{\"productId\":\"00000000-0000-0000-0000-000000000001\",\"quantity\":1,\"unitAmount\":10.5,\"taxClassCode\":\"phase4c-test\"}],\"shipping\":\"phase4c-test\",\"languageCode\":\"phase4c-test\",\"idempotencyKey\":\"phase4c-test\"}" "quoteId" 200 || true
assert_json_field 14 "Business rule assertion: BR-TAX-CAL-002" BR-TAX-CAL-002 POST "$BASE_URL/tax-calculations" "{\"currencyCode\":\"phase4c-test\",\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"orderId\":\"00000000-0000-0000-0000-000000000001\",\"billingAddress\":{\"countryCode\":\"phase4c-test\",\"zoneCode\":\"phase4c-test\",\"stateProvince\":\"phase4c-test\"},\"shippingAddress\":\"phase4c-test\",\"items\":[{\"productId\":\"00000000-0000-0000-0000-000000000001\",\"quantity\":1,\"unitAmount\":10.5,\"taxClassCode\":\"phase4c-test\"}],\"shipping\":\"phase4c-test\",\"languageCode\":\"phase4c-test\",\"idempotencyKey\":\"phase4c-test\"}" "quoteId" 200 || true
assert_json_field 15 "Business rule assertion: BR-TAX-CAL-003" BR-TAX-CAL-003 POST "$BASE_URL/tax-calculations" "{\"currencyCode\":\"phase4c-test\",\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"orderId\":\"00000000-0000-0000-0000-000000000001\",\"billingAddress\":{\"countryCode\":\"phase4c-test\",\"zoneCode\":\"phase4c-test\",\"stateProvince\":\"phase4c-test\"},\"shippingAddress\":\"phase4c-test\",\"items\":[{\"productId\":\"00000000-0000-0000-0000-000000000001\",\"quantity\":1,\"unitAmount\":10.5,\"taxClassCode\":\"phase4c-test\"}],\"shipping\":\"phase4c-test\",\"languageCode\":\"phase4c-test\",\"idempotencyKey\":\"phase4c-test\"}" "quoteId" 200 || true
assert_json_field 16 "Business rule assertion: BR-TAX-CAL-004" BR-TAX-CAL-004 POST "$BASE_URL/tax-calculations" "{\"currencyCode\":\"phase4c-test\",\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"orderId\":\"00000000-0000-0000-0000-000000000001\",\"billingAddress\":{\"countryCode\":\"phase4c-test\",\"zoneCode\":\"phase4c-test\",\"stateProvince\":\"phase4c-test\"},\"shippingAddress\":\"phase4c-test\",\"items\":[{\"productId\":\"00000000-0000-0000-0000-000000000001\",\"quantity\":1,\"unitAmount\":10.5,\"taxClassCode\":\"phase4c-test\"}],\"shipping\":\"phase4c-test\",\"languageCode\":\"phase4c-test\",\"idempotencyKey\":\"phase4c-test\"}" "quoteId" 200 || true
assert_json_field 17 "Business rule assertion: BR-TAX-CAL-005" BR-TAX-CAL-005 POST "$BASE_URL/tax-calculations" "{\"currencyCode\":\"phase4c-test\",\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"orderId\":\"00000000-0000-0000-0000-000000000001\",\"billingAddress\":{\"countryCode\":\"phase4c-test\",\"zoneCode\":\"phase4c-test\",\"stateProvince\":\"phase4c-test\"},\"shippingAddress\":\"phase4c-test\",\"items\":[{\"productId\":\"00000000-0000-0000-0000-000000000001\",\"quantity\":1,\"unitAmount\":10.5,\"taxClassCode\":\"phase4c-test\"}],\"shipping\":\"phase4c-test\",\"languageCode\":\"phase4c-test\",\"idempotencyKey\":\"phase4c-test\"}" "quoteId" 200 || true
assert_json_field 18 "Business rule assertion: BR-TAX-CAL-006" BR-TAX-CAL-006 POST "$BASE_URL/tax-calculations" "{\"currencyCode\":\"phase4c-test\",\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"orderId\":\"00000000-0000-0000-0000-000000000001\",\"billingAddress\":{\"countryCode\":\"phase4c-test\",\"zoneCode\":\"phase4c-test\",\"stateProvince\":\"phase4c-test\"},\"shippingAddress\":\"phase4c-test\",\"items\":[{\"productId\":\"00000000-0000-0000-0000-000000000001\",\"quantity\":1,\"unitAmount\":10.5,\"taxClassCode\":\"phase4c-test\"}],\"shipping\":\"phase4c-test\",\"languageCode\":\"phase4c-test\",\"idempotencyKey\":\"phase4c-test\"}" "quoteId" 200 || true
assert_json_field 19 "Business rule assertion: BR-TAX-CAL-007" BR-TAX-CAL-007 POST "$BASE_URL/tax-calculations" "{\"currencyCode\":\"phase4c-test\",\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"orderId\":\"00000000-0000-0000-0000-000000000001\",\"billingAddress\":{\"countryCode\":\"phase4c-test\",\"zoneCode\":\"phase4c-test\",\"stateProvince\":\"phase4c-test\"},\"shippingAddress\":\"phase4c-test\",\"items\":[{\"productId\":\"00000000-0000-0000-0000-000000000001\",\"quantity\":1,\"unitAmount\":10.5,\"taxClassCode\":\"phase4c-test\"}],\"shipping\":\"phase4c-test\",\"languageCode\":\"phase4c-test\",\"idempotencyKey\":\"phase4c-test\"}" "quoteId" 200 || true
assert_json_field 20 "Business rule assertion: BR-TAX-CAL-008" BR-TAX-CAL-008 POST "$BASE_URL/tax-calculations" "{\"currencyCode\":\"phase4c-test\",\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"orderId\":\"00000000-0000-0000-0000-000000000001\",\"billingAddress\":{\"countryCode\":\"phase4c-test\",\"zoneCode\":\"phase4c-test\",\"stateProvince\":\"phase4c-test\"},\"shippingAddress\":\"phase4c-test\",\"items\":[{\"productId\":\"00000000-0000-0000-0000-000000000001\",\"quantity\":1,\"unitAmount\":10.5,\"taxClassCode\":\"phase4c-test\"}],\"shipping\":\"phase4c-test\",\"languageCode\":\"phase4c-test\",\"idempotencyKey\":\"phase4c-test\"}" "quoteId" 200 || true
assert_json_field 21 "Business rule assertion: BR-TAX-CAL-009" BR-TAX-CAL-009 POST "$BASE_URL/tax-calculations" "{\"currencyCode\":\"phase4c-test\",\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"orderId\":\"00000000-0000-0000-0000-000000000001\",\"billingAddress\":{\"countryCode\":\"phase4c-test\",\"zoneCode\":\"phase4c-test\",\"stateProvince\":\"phase4c-test\"},\"shippingAddress\":\"phase4c-test\",\"items\":[{\"productId\":\"00000000-0000-0000-0000-000000000001\",\"quantity\":1,\"unitAmount\":10.5,\"taxClassCode\":\"phase4c-test\"}],\"shipping\":\"phase4c-test\",\"languageCode\":\"phase4c-test\",\"idempotencyKey\":\"phase4c-test\"}" "quoteId" 200 || true
assert_json_field 22 "Business rule assertion: BR-TAX-CAL-010" BR-TAX-CAL-010 POST "$BASE_URL/tax-calculations" "{\"currencyCode\":\"phase4c-test\",\"customerId\":\"00000000-0000-0000-0000-000000000001\",\"orderId\":\"00000000-0000-0000-0000-000000000001\",\"billingAddress\":{\"countryCode\":\"phase4c-test\",\"zoneCode\":\"phase4c-test\",\"stateProvince\":\"phase4c-test\"},\"shippingAddress\":\"phase4c-test\",\"items\":[{\"productId\":\"00000000-0000-0000-0000-000000000001\",\"quantity\":1,\"unitAmount\":10.5,\"taxClassCode\":\"phase4c-test\"}],\"shipping\":\"phase4c-test\",\"languageCode\":\"phase4c-test\",\"idempotencyKey\":\"phase4c-test\"}" "quoteId" 200 || true
assert_json_field 23 "Contract success: POST /tax-classes" BR-TAX-CFG-001 POST "$BASE_URL/tax-classes" "{\"code\":\"phase4c-test\",\"title\":\"phase4c-test\"}" "id" 201 || true
assert_status 24 "Contract error/conformance: POST /tax-classes" BR-TAX-CFG-001 POST "$BASE_URL/tax-classes" "{}" 400 || true
assert_json_field 25 "Contract success: POST /tax-rates" BR-TAX-CFG-001 POST "$BASE_URL/tax-rates" "{\"taxClassCode\":\"phase4c-test\",\"code\":\"phase4c-test\",\"rate\":10.5,\"priority\":1,\"piggyback\":true,\"countryCode\":\"phase4c-test\",\"zoneCode\":\"phase4c-test\",\"stateProvince\":\"phase4c-test\",\"descriptions\":[{\"id\":\"00000000-0000-0000-0000-000000000001\",\"languageCode\":\"phase4c-test\",\"name\":\"phase4c-test\",\"title\":\"phase4c-test\",\"description\":\"phase4c-test\"}]}" "id" 201 || true
assert_status 26 "Contract error/conformance: POST /tax-rates" BR-TAX-CFG-001 POST "$BASE_URL/tax-rates" "{}" 400 || true
assert_json_field 27 "Contract success: GET /tax-classes" BR-TAX-CFG-001 GET "$BASE_URL/tax-classes" "null" "items" 200 || true
assert_status 28 "Contract error/conformance: GET /tax-classes" BR-TAX-CFG-001 GET "$BASE_URL/tax-classes" "null" 400 || true
assert_json_field 29 "Contract success: GET /tax-classes/exists" BR-TAX-CFG-001 GET "$BASE_URL/tax-classes/exists" "null" "exists" 200 || true
assert_status 30 "Contract error/conformance: GET /tax-classes/exists" BR-TAX-CFG-001 GET "$BASE_URL/tax-classes/exists" "null" 400 || true
assert_json_field 31 "Contract success: GET /tax-classes/{id}" BR-TAX-CFG-001 GET "$BASE_URL/tax-classes/${RESOURCE_ID}" "null" "id" 200 || true
assert_status 32 "Contract error/conformance: GET /tax-classes/{id}" BR-TAX-CFG-001 GET "$BASE_URL/tax-classes/${RESOURCE_ID}" "null" 401 || true
assert_json_field 33 "Contract success: GET /tax-configuration" BR-TAX-CFG-001 GET "$BASE_URL/tax-configuration" "null" "taxBasis" 200 || true
assert_status 34 "Contract error/conformance: GET /tax-configuration" BR-TAX-CFG-001 GET "$BASE_URL/tax-configuration" "null" 401 || true
assert_json_field 35 "Contract success: GET /tax-rates" BR-TAX-CFG-001 GET "$BASE_URL/tax-rates" "null" "items" 200 || true
assert_status 36 "Contract error/conformance: GET /tax-rates" BR-TAX-CFG-001 GET "$BASE_URL/tax-rates" "null" 400 || true
assert_json_field 37 "Contract success: GET /tax-rates/exists" BR-TAX-CFG-001 GET "$BASE_URL/tax-rates/exists" "null" "exists" 200 || true
assert_status 38 "Contract error/conformance: GET /tax-rates/exists" BR-TAX-CFG-001 GET "$BASE_URL/tax-rates/exists" "null" 400 || true
assert_json_field 39 "Contract success: GET /tax-rates/{id}" BR-TAX-CFG-001 GET "$BASE_URL/tax-rates/${RESOURCE_ID}" "null" "id" 200 || true
assert_status 40 "Contract error/conformance: GET /tax-rates/{id}" BR-TAX-CFG-001 GET "$BASE_URL/tax-rates/${RESOURCE_ID}" "null" 401 || true
assert_json_field 41 "Contract success: PUT /tax-classes/{id}" BR-TAX-CFG-001 PUT "$BASE_URL/tax-classes/${RESOURCE_ID}" "{\"code\":\"phase4c-test\",\"title\":\"phase4c-test\"}" "id" 200 || true
assert_status 42 "Contract error/conformance: PUT /tax-classes/{id}" BR-TAX-CFG-001 PUT "$BASE_URL/tax-classes/${RESOURCE_ID}" "{}" 400 || true
assert_json_field 43 "Contract success: PUT /tax-configuration" BR-TAX-CFG-001 PUT "$BASE_URL/tax-configuration" "{\"taxBasis\":\"StoreAddress\",\"collectTaxIfDifferentProvince\":true,\"differentCountryBehavior\":\"UseCustomerJurisdiction\"}" "taxBasis" 200 || true
assert_status 44 "Contract error/conformance: PUT /tax-configuration" BR-TAX-CFG-001 PUT "$BASE_URL/tax-configuration" "{}" 400 || true
assert_json_field 45 "Contract success: PUT /tax-rates/{id}" BR-TAX-CFG-001 PUT "$BASE_URL/tax-rates/${RESOURCE_ID}" "{}" "id" 200 || true
assert_status 46 "Contract error/conformance: PUT /tax-rates/{id}" BR-TAX-CFG-001 PUT "$BASE_URL/tax-rates/${RESOURCE_ID}" "{}" 400 || true
assert_json_field 47 "Contract success: DELETE /tax-classes/{id}" BR-TAX-CFG-001 DELETE "$BASE_URL/tax-classes/${RESOURCE_ID}" "null" "deleted" 200 || true
assert_status 48 "Contract error/conformance: DELETE /tax-classes/{id}" BR-TAX-CFG-001 DELETE "$BASE_URL/tax-classes/${RESOURCE_ID}" "null" 401 || true
assert_json_field 49 "Contract success: DELETE /tax-rates/{id}" BR-TAX-CFG-001 DELETE "$BASE_URL/tax-rates/${RESOURCE_ID}" "null" "deleted" 200 || true
assert_status 50 "Contract error/conformance: DELETE /tax-rates/{id}" BR-TAX-CFG-001 DELETE "$BASE_URL/tax-rates/${RESOURCE_ID}" "null" 401 || true

echo -e "\n=============================================="
echo "Results: $PASSED passed, $FAILED failed, $TOTAL total"
if [ "$FAILED" -eq 0 ]; then
    echo "ALL  + str(test_num - 1) +  TESTS PASSED - 100% SUCCESS"
    exit 0
fi
echo "TEST SUITE FAILED"
printf '%s\n' "${FAILED_TESTS[@]}"
exit 1
