using Npgsql;

namespace Shopizer.OrderManagement.Data;

public sealed class SchemaInitializer(NpgsqlDataSource dataSource, ILogger<SchemaInitializer> logger)
{
    public async Task InitializeAsync(CancellationToken ct)
    {
        await using var connection = await dataSource.OpenConnectionAsync(ct);
        await EnsurePgCryptoAsync(connection, ct);
        await using (var command = new NpgsqlCommand(SchemaSql, connection)) await command.ExecuteNonQueryAsync(ct);
        await using (var command = new NpgsqlCommand(MigrationSql, connection)) await command.ExecuteNonQueryAsync(ct);
        logger.LogInformation("Order management PostgreSQL schema is ready.");
    }

    private static async Task EnsurePgCryptoAsync(NpgsqlConnection connection, CancellationToken ct)
    {
        try
        {
            await using var command = new NpgsqlCommand("CREATE EXTENSION IF NOT EXISTS pgcrypto", connection);
            await command.ExecuteNonQueryAsync(ct);
        }
        catch (PostgresException ex) when (ex.SqlState == PostgresErrorCodes.UniqueViolation && ex.ConstraintName == "pg_extension_name_index")
        {
        }
    }

    private const string SchemaSql = """
        CREATE SCHEMA IF NOT EXISTS order_management;
        CREATE TABLE IF NOT EXISTS order_management.orders (
          order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          tenant_id VARCHAR(100) NOT NULL, store_id BIGINT NOT NULL, customer_id BIGINT,
          customer_email_address VARCHAR(255) NOT NULL, order_status VARCHAR(20) NOT NULL DEFAULT 'ORDERED',
          order_channel VARCHAR(30), order_type VARCHAR(30) NOT NULL DEFAULT 'ORDER',
          date_purchased TIMESTAMPTZ NOT NULL, order_date_finished TIMESTAMPTZ,
          last_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, currency_id BIGINT,
          currency_code CHAR(3) NOT NULL, currency_value NUMERIC(19,4) NOT NULL DEFAULT 1.0000,
          order_total NUMERIC(19,4) NOT NULL, ip_address INET, cart_code VARCHAR(255),
          payment_type VARCHAR(40), payment_module_code VARCHAR(100), shipping_module_code VARCHAR(100),
          customer_agreed BOOLEAN NOT NULL DEFAULT FALSE, confirmed_address BOOLEAN NOT NULL DEFAULT FALSE,
          locale VARCHAR(20), payment_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
          fulfillment_status VARCHAR(30) NOT NULL DEFAULT 'NOT_REQUESTED',
          refundable_amount NUMERIC(19,4) NOT NULL DEFAULT 0, refunded_amount NUMERIC(19,4) NOT NULL DEFAULT 0,
          version BIGINT NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by VARCHAR(100),
          correlation_id VARCHAR(100), submission_id VARCHAR(255),
          CONSTRAINT ck_orders_status CHECK(order_status IN ('ORDERED','PROCESSED','DELIVERED','REFUNDED','CANCELED')),
          CONSTRAINT ck_orders_payment_status CHECK(payment_status IN ('PENDING','AUTHORIZED','CAPTURED','FAILED','REFUNDED','VOIDED','UNKNOWN')),
          CONSTRAINT ck_orders_fulfillment_status CHECK(fulfillment_status IN ('NOT_REQUESTED','REQUESTED','IN_PROGRESS','SHIPPED','DELIVERED','CANCELED')),
          CONSTRAINT ck_orders_total_nonnegative CHECK(order_total >= 0),
          CONSTRAINT ck_orders_refund_nonnegative CHECK(refunded_amount >= 0),
          CONSTRAINT ck_orders_refundable_nonnegative CHECK(refundable_amount >= 0),
          CONSTRAINT uq_orders_submission_context UNIQUE(tenant_id,store_id,submission_id)
        );
        CREATE TABLE IF NOT EXISTS order_management.order_billing_address (
          order_id BIGINT PRIMARY KEY REFERENCES order_management.orders(order_id) ON DELETE CASCADE,
          first_name VARCHAR(100), last_name VARCHAR(100), company VARCHAR(255), address VARCHAR(255),
          city VARCHAR(100), state VARCHAR(100), country_code CHAR(2), zone_code VARCHAR(100),
          postal_code VARCHAR(30), telephone VARCHAR(50),
          CONSTRAINT ck_billing_country_or_state CHECK(country_code IS NOT NULL OR state IS NOT NULL)
        );
        CREATE TABLE IF NOT EXISTS order_management.order_delivery_address (
          order_id BIGINT PRIMARY KEY REFERENCES order_management.orders(order_id) ON DELETE CASCADE,
          first_name VARCHAR(100), last_name VARCHAR(100), company VARCHAR(255), address VARCHAR(255),
          city VARCHAR(100), state VARCHAR(100), country_code CHAR(2), zone_code VARCHAR(100),
          postal_code VARCHAR(30), telephone VARCHAR(50),
          CONSTRAINT ck_delivery_country_or_state CHECK(country_code IS NOT NULL OR state IS NOT NULL)
        );
        CREATE TABLE IF NOT EXISTS order_management.order_products (
          order_product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          order_id BIGINT NOT NULL REFERENCES order_management.orders(order_id) ON DELETE CASCADE,
          product_sku VARCHAR(255), product_name VARCHAR(64) NOT NULL, product_quantity INTEGER NOT NULL,
          onetime_charge NUMERIC(19,4) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          CONSTRAINT ck_order_products_quantity_positive CHECK(product_quantity > 0),
          CONSTRAINT ck_order_products_charge_nonnegative CHECK(onetime_charge >= 0)
        );
        CREATE TABLE IF NOT EXISTS order_management.order_product_attributes (
          order_product_attribute_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          order_product_id BIGINT NOT NULL REFERENCES order_management.order_products(order_product_id) ON DELETE CASCADE,
          product_attribute_price NUMERIC(19,4) NOT NULL DEFAULT 0, product_attribute_is_free BOOLEAN NOT NULL DEFAULT FALSE,
          product_attribute_weight NUMERIC(19,4), product_option_id BIGINT NOT NULL, product_option_value_id BIGINT NOT NULL,
          product_attribute_name VARCHAR(255), product_attribute_val_name VARCHAR(255),
          CONSTRAINT ck_attribute_price_nonnegative CHECK(product_attribute_price >= 0)
        );
        CREATE TABLE IF NOT EXISTS order_management.order_product_prices (
          order_product_price_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          order_product_id BIGINT NOT NULL REFERENCES order_management.order_products(order_product_id) ON DELETE CASCADE,
          product_price_code VARCHAR(64) NOT NULL, product_price NUMERIC(19,4) NOT NULL,
          product_price_special NUMERIC(19,4), prd_price_special_st_dt TIMESTAMPTZ,
          prd_price_special_end_dt TIMESTAMPTZ, default_price BOOLEAN NOT NULL, product_price_name VARCHAR(255)
        );
        CREATE TABLE IF NOT EXISTS order_management.order_product_downloads (
          order_product_download_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          order_product_id BIGINT NOT NULL REFERENCES order_management.order_products(order_product_id) ON DELETE CASCADE,
          order_product_filename VARCHAR(1024) NOT NULL, download_maxdays INTEGER NOT NULL DEFAULT 31,
          download_count INTEGER NOT NULL DEFAULT 0, access_state VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
          expires_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          CONSTRAINT ck_download_count_nonnegative CHECK(download_count >= 0),
          CONSTRAINT ck_download_maxdays_positive CHECK(download_maxdays > 0),
          CONSTRAINT ck_download_access_state CHECK(access_state IN ('AVAILABLE','EXPIRED','REVOKED'))
        );
        CREATE TABLE IF NOT EXISTS order_management.order_totals (
          order_total_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          order_id BIGINT NOT NULL REFERENCES order_management.orders(order_id) ON DELETE CASCADE,
          code VARCHAR(255) NOT NULL, title VARCHAR(255), text TEXT, value NUMERIC(19,4) NOT NULL,
          module VARCHAR(60), order_value_type VARCHAR(20) NOT NULL DEFAULT 'ONE_TIME',
          order_total_type VARCHAR(20), sort_order INTEGER NOT NULL DEFAULT 0, is_refund BOOLEAN NOT NULL DEFAULT FALSE,
          CONSTRAINT ck_order_total_value_type CHECK(order_value_type IN ('ONE_TIME','MONTHLY')),
          CONSTRAINT ck_order_total_type CHECK(order_total_type IS NULL OR order_total_type IN ('SHIPPING','HANDLING','TAX','PRODUCT','SUBTOTAL','TOTAL','CREDIT','REFUND'))
        );
        CREATE TABLE IF NOT EXISTS order_management.order_attributes (
          order_attribute_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          order_id BIGINT NOT NULL REFERENCES order_management.orders(order_id) ON DELETE CASCADE,
          identifier VARCHAR(255) NOT NULL, value TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS order_management.order_status_history (
          order_status_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          order_id BIGINT NOT NULL REFERENCES order_management.orders(order_id) ON DELETE CASCADE,
          status VARCHAR(20), date_added TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          customer_notified BOOLEAN NOT NULL DEFAULT FALSE, comments TEXT, actor_id VARCHAR(100),
          source VARCHAR(40) NOT NULL, event_id VARCHAR(100),
          CONSTRAINT ck_history_status CHECK(status IS NULL OR status IN ('ORDERED','PROCESSED','DELIVERED','REFUNDED','CANCELED')),
          CONSTRAINT uq_history_event UNIQUE(order_id,event_id)
        );
        CREATE TABLE IF NOT EXISTS order_management.payment_outcomes (
          transaction_id VARCHAR(255) PRIMARY KEY, tenant_id VARCHAR(100) NOT NULL, store_id BIGINT NOT NULL,
          order_id BIGINT NOT NULL REFERENCES order_management.orders(order_id) ON DELETE CASCADE,
          action VARCHAR(30) NOT NULL, status VARCHAR(20) NOT NULL, amount NUMERIC(19,4) NOT NULL,
          currency CHAR(3) NOT NULL, payment_reference VARCHAR(255), occurred_at TIMESTAMPTZ NOT NULL,
          event_id VARCHAR(255) UNIQUE
        );
        CREATE TABLE IF NOT EXISTS order_management.refund_applications (
          refund_id VARCHAR(255) PRIMARY KEY, tenant_id VARCHAR(100) NOT NULL, store_id BIGINT NOT NULL,
          order_id BIGINT NOT NULL REFERENCES order_management.orders(order_id) ON DELETE CASCADE,
          amount NUMERIC(19,4) NOT NULL CHECK(amount > 0), currency CHAR(3) NOT NULL, reason TEXT NOT NULL,
          status VARCHAR(20) NOT NULL DEFAULT 'PROCESSING', idempotency_key VARCHAR(255) NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, applied_at TIMESTAMPTZ,
          UNIQUE(tenant_id,store_id,idempotency_key)
        );
        CREATE TABLE IF NOT EXISTS order_management.fulfillment_orders (
          fulfillment_order_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          order_id BIGINT NOT NULL REFERENCES order_management.orders(order_id) ON DELETE RESTRICT,
          tenant_id VARCHAR(100) NOT NULL, store_id BIGINT NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'REQUESTED',
          requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, last_updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          carrier_reference VARCHAR(255), version BIGINT NOT NULL DEFAULT 0,
          CONSTRAINT uq_fulfillment_order_order UNIQUE(tenant_id,store_id,order_id),
          CONSTRAINT ck_fulfillment_status CHECK(status IN ('REQUESTED','IN_PROGRESS','SHIPPED','DELIVERED','CANCELED'))
        );
        CREATE TABLE IF NOT EXISTS order_management.fulfillment_status_history (
          fulfillment_status_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          fulfillment_order_id UUID NOT NULL REFERENCES order_management.fulfillment_orders(fulfillment_order_id) ON DELETE CASCADE,
          status VARCHAR(30) NOT NULL, occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          source VARCHAR(40) NOT NULL, external_reference VARCHAR(255)
        );
        CREATE TABLE IF NOT EXISTS order_management.order_inbox (
          inbox_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id VARCHAR(100) NOT NULL,
          store_id BIGINT NOT NULL, message_id VARCHAR(255) NOT NULL, message_type VARCHAR(120) NOT NULL,
          idempotency_key VARCHAR(255), received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          processed_at TIMESTAMPTZ, processing_status VARCHAR(20) NOT NULL DEFAULT 'RECEIVED', response_body JSONB,
          CONSTRAINT uq_order_inbox_message UNIQUE(tenant_id,store_id,message_id),
          CONSTRAINT uq_order_inbox_idempotency UNIQUE(tenant_id,store_id,idempotency_key),
          CONSTRAINT ck_inbox_status CHECK(processing_status IN ('RECEIVED','PROCESSED','FAILED'))
        );
        CREATE TABLE IF NOT EXISTS order_management.order_outbox (
          outbox_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id VARCHAR(100) NOT NULL,
          store_id BIGINT NOT NULL, aggregate_type VARCHAR(80) NOT NULL, aggregate_id BIGINT NOT NULL,
          event_id UUID NOT NULL DEFAULT gen_random_uuid(), event_type VARCHAR(120) NOT NULL, event_version INTEGER NOT NULL DEFAULT 1,
          payload JSONB NOT NULL, occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, published_at TIMESTAMPTZ,
          delivery_attempts INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_order_outbox_event UNIQUE(event_id)
        );
        CREATE TABLE IF NOT EXISTS order_management.invoice_requests (
          request_id VARCHAR(255) PRIMARY KEY, tenant_id VARCHAR(100) NOT NULL, store_id BIGINT NOT NULL,
          order_id BIGINT NOT NULL REFERENCES order_management.orders(order_id) ON DELETE CASCADE,
          status VARCHAR(20) NOT NULL DEFAULT 'PROCESSING', artifact_url VARCHAR(2048), generated_at TIMESTAMPTZ,
          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(tenant_id,store_id,order_id)
        );
        CREATE TABLE IF NOT EXISTS order_management.cancellation_records (
          cancellation_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id VARCHAR(100) NOT NULL, store_id BIGINT NOT NULL,
          order_id BIGINT NOT NULL REFERENCES order_management.orders(order_id) ON DELETE CASCADE,
          reason TEXT NOT NULL, compensation_state VARCHAR(20) NOT NULL DEFAULT 'PENDING',
          idempotency_key VARCHAR(255) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          UNIQUE(tenant_id,store_id,idempotency_key)
        );
        CREATE INDEX IF NOT EXISTS ix_orders_tenant_store_status ON order_management.orders(tenant_id,store_id,order_status);
        CREATE INDEX IF NOT EXISTS ix_orders_tenant_store_customer ON order_management.orders(tenant_id,store_id,customer_id,date_purchased DESC);
        CREATE INDEX IF NOT EXISTS ix_orders_tenant_store_email ON order_management.orders(tenant_id,store_id,customer_email_address);
        CREATE INDEX IF NOT EXISTS ix_orders_last_modified ON order_management.orders(tenant_id,store_id,last_modified DESC);
        CREATE INDEX IF NOT EXISTS ix_order_products_order ON order_management.order_products(order_id);
        CREATE INDEX IF NOT EXISTS ix_order_product_attributes_product ON order_management.order_product_attributes(order_product_id);
        CREATE INDEX IF NOT EXISTS ix_order_product_prices_product ON order_management.order_product_prices(order_product_id);
        CREATE INDEX IF NOT EXISTS ix_order_product_downloads_product ON order_management.order_product_downloads(order_product_id,access_state);
        CREATE INDEX IF NOT EXISTS ix_order_totals_order_sort ON order_management.order_totals(order_id,sort_order);
        CREATE INDEX IF NOT EXISTS ix_order_history_order_date ON order_management.order_status_history(order_id,date_added DESC);
        CREATE INDEX IF NOT EXISTS ix_fulfillment_status_order ON order_management.fulfillment_orders(tenant_id,store_id,status);
        CREATE INDEX IF NOT EXISTS ix_outbox_unpublished ON order_management.order_outbox(published_at,occurred_at) WHERE published_at IS NULL;
        """;

    private const string MigrationSql = """
        ALTER TABLE order_management.orders ADD COLUMN IF NOT EXISTS submission_id VARCHAR(255);
        ALTER TABLE order_management.order_status_history ADD COLUMN IF NOT EXISTS event_id VARCHAR(100);
        ALTER TABLE order_management.order_status_history ADD COLUMN IF NOT EXISTS customer_notified BOOLEAN NOT NULL DEFAULT FALSE;
        ALTER TABLE order_management.order_inbox ADD COLUMN IF NOT EXISTS response_body JSONB;
        ALTER TABLE order_management.order_outbox ADD COLUMN IF NOT EXISTS delivery_attempts INTEGER NOT NULL DEFAULT 0;
        """;
}
