$schema: https://json-schema.org/draft/2020-12/schema
title: ConfigurationReferenceChanged
type: object
allOf:
  - $ref: ../common-schemas.yaml#/components/schemas/EventMetadata
  - type: object
    required: [eventType, eventVersion, moduleType, code, environment, configurationRef, version]
    properties:
      eventType: {const: ConfigurationReferenceChanged}
      eventVersion: {const: 1}
      moduleType: {type: string, enum: [Email, Shipping, Maps, Storage, Adapter]}
      code: {type: string}
      environment: {type: string}
      configurationRef: {type: string}
      version: {type: string}
