$schema: https://json-schema.org/draft/2020-12/schema
title: ProductChanged.v1
type: object
allOf:
  - $ref: ../common-schemas.yaml#/components/schemas/EventMetadata
  - type: object
    required: [eventType, eventVersion, aggregateId, aggregateVersion, changeType, product]
    properties:
      eventType: {const: ProductChanged.v1}
      eventVersion: {const: 1}
      aggregateId: {type: string}
      aggregateVersion: {type: integer}
      changeType: {type: string}
      product:
        $ref: ../../microservices/ms-02/04-api-contract.yaml#/components/schemas/Product
