using Npgsql;

namespace Shopizer.CartCheckout.Data;

public sealed class SchemaInitializer(NpgsqlDataSource dataSource, ILogger<SchemaInitializer> logger)
{
    public async Task InitializeAsync(CancellationToken ct)
    {
        await using var connection = await dataSource.OpenConnectionAsync(ct);
        await EnsurePgCryptoAsync(connection, ct);
        await using var schema = new NpgsqlCommand(SchemaSql, connection);
        await schema.ExecuteNonQueryAsync(ct);
        await using var migration = new NpgsqlCommand(MigrationSql, connection);
        await migration.ExecuteNonQueryAsync(ct);
        logger.LogInformation("Cart and checkout PostgreSQL schema is ready.");
    }

    private static async Task EnsurePgCryptoAsync(NpgsqlConnection connection, CancellationToken ct)
    {
        try
        {
            await using var command = new NpgsqlCommand("CREATE EXTENSION IF NOT EXISTS pgcrypto", connection);
            await command.ExecuteNonQueryAsync(ct);
        }
        catch (PostgresException ex) when (ex.SqlState == PostgresErrorCodes.UniqueViolation && ex.ConstraintName == "pg_extension_name_index")
        {
        }
    }

    private const string SchemaSql = """
        CREATE SCHEMA IF NOT EXISTS cart_checkout_schema;
        DO $$ BEGIN CREATE TYPE cart_checkout_schema.cart_status AS ENUM ('OPEN','COMPLETED','OBSOLETE'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
        DO $$ BEGIN CREATE TYPE cart_checkout_schema.checkout_state AS ENUM ('OPEN','QUOTED','FROZEN','SUBMITTED','FAILED','EXPIRED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
        DO $$ BEGIN CREATE TYPE cart_checkout_schema.quote_kind AS ENUM ('PRICING','PROMOTION','TAX','SHIPPING'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
        DO $$ BEGIN CREATE TYPE cart_checkout_schema.submission_state AS ENUM ('PENDING','SUBMITTED','ACKNOWLEDGED','FAILED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
        DO $$ BEGIN CREATE TYPE cart_checkout_schema.idempotency_state AS ENUM ('IN_PROGRESS','COMPLETED','FAILED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
        DO $$ BEGIN CREATE TYPE cart_checkout_schema.outbox_state AS ENUM ('PENDING','PUBLISHED','FAILED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
        CREATE TABLE IF NOT EXISTS cart_checkout_schema.shopping_cart (
          cart_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, cart_code varchar(128) NOT NULL,
          tenant_id varchar(128) NOT NULL, store_id varchar(128) NOT NULL, customer_id bigint, submitted_order_id uuid,
          status cart_checkout_schema.cart_status NOT NULL DEFAULT 'OPEN', ip_address inet, promo_code varchar(128),
          promo_added_at timestamptz, currency_code char(3) NOT NULL DEFAULT 'CAD', created_at timestamptz NOT NULL DEFAULT current_timestamp,
          updated_at timestamptz NOT NULL DEFAULT current_timestamp, created_by varchar(128), updated_by varchar(128),
          correlation_id uuid, CONSTRAINT shopping_cart_code_unique UNIQUE(tenant_id,store_id,cart_code),
          CONSTRAINT shopping_cart_completed_reference_check CHECK((status='COMPLETED' AND submitted_order_id IS NOT NULL) OR status <> 'COMPLETED'),
          CONSTRAINT shopping_cart_currency_check CHECK(currency_code ~ '^[A-Z]{3}$'));
        CREATE INDEX IF NOT EXISTS shopping_cart_customer_idx ON cart_checkout_schema.shopping_cart(tenant_id,store_id,customer_id) WHERE status='OPEN';
        CREATE INDEX IF NOT EXISTS shopping_cart_status_idx ON cart_checkout_schema.shopping_cart(tenant_id,store_id,status);
        CREATE TABLE IF NOT EXISTS cart_checkout_schema.shopping_cart_item (
          cart_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, cart_id bigint NOT NULL REFERENCES cart_checkout_schema.shopping_cart(cart_id) ON DELETE CASCADE,
          product_id bigint NOT NULL, sku varchar(128) NOT NULL, variant_id bigint, quantity integer NOT NULL,
          item_price numeric(19,4) NOT NULL, sub_total numeric(19,4) NOT NULL, obsolete boolean NOT NULL DEFAULT false,
          created_at timestamptz NOT NULL DEFAULT current_timestamp, updated_at timestamptz NOT NULL DEFAULT current_timestamp,
          CONSTRAINT shopping_cart_item_quantity_check CHECK(quantity>0), CONSTRAINT shopping_cart_item_money_check CHECK(item_price>=0 AND sub_total>=0));
        CREATE INDEX IF NOT EXISTS shopping_cart_item_cart_idx ON cart_checkout_schema.shopping_cart_item(cart_id);
        CREATE INDEX IF NOT EXISTS shopping_cart_item_sku_idx ON cart_checkout_schema.shopping_cart_item(cart_id,sku);
        CREATE TABLE IF NOT EXISTS cart_checkout_schema.shopping_cart_attr_item (
          cart_attribute_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, cart_item_id bigint NOT NULL REFERENCES cart_checkout_schema.shopping_cart_item(cart_item_id) ON DELETE CASCADE,
          product_attribute_id bigint NOT NULL, created_at timestamptz NOT NULL DEFAULT current_timestamp,
          updated_at timestamptz NOT NULL DEFAULT current_timestamp, CONSTRAINT shopping_cart_attr_unique UNIQUE(cart_item_id,product_attribute_id));
        CREATE TABLE IF NOT EXISTS cart_checkout_schema.checkout_session (
          checkout_session_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), cart_id bigint NOT NULL REFERENCES cart_checkout_schema.shopping_cart(cart_id),
          customer_id bigint, tenant_id varchar(128) NOT NULL, store_id varchar(128) NOT NULL, state cart_checkout_schema.checkout_state NOT NULL DEFAULT 'OPEN',
          cart_version bigint NOT NULL DEFAULT 0, currency_code char(3) NOT NULL, expires_at timestamptz NOT NULL,
          submitted_at timestamptz, failure_code varchar(128), created_at timestamptz NOT NULL DEFAULT current_timestamp,
          updated_at timestamptz NOT NULL DEFAULT current_timestamp, correlation_id uuid,
          CONSTRAINT checkout_session_currency_check CHECK(currency_code ~ '^[A-Z]{3}$'));
        CREATE INDEX IF NOT EXISTS checkout_session_cart_idx ON cart_checkout_schema.checkout_session(tenant_id,store_id,cart_id,state);
        CREATE INDEX IF NOT EXISTS checkout_session_expiry_idx ON cart_checkout_schema.checkout_session(tenant_id,store_id,expires_at) WHERE state IN('OPEN','QUOTED','FROZEN');
        CREATE TABLE IF NOT EXISTS cart_checkout_schema.checkout_line_snapshot (
          checkout_line_snapshot_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), checkout_session_id uuid NOT NULL REFERENCES cart_checkout_schema.checkout_session(checkout_session_id) ON DELETE CASCADE,
          line_number integer NOT NULL, sku varchar(128) NOT NULL, product_name varchar(255) NOT NULL, quantity integer NOT NULL,
          unit_price numeric(19,4) NOT NULL, line_sub_total numeric(19,4) NOT NULL, product_id bigint NOT NULL, variant_id bigint,
          is_virtual boolean NOT NULL DEFAULT false, attributes jsonb NOT NULL DEFAULT '[]'::jsonb, created_at timestamptz NOT NULL DEFAULT current_timestamp,
          CONSTRAINT checkout_line_quantity_check CHECK(quantity>0), CONSTRAINT checkout_line_money_check CHECK(unit_price>=0 AND line_sub_total>=0),
          CONSTRAINT checkout_line_number_unique UNIQUE(checkout_session_id,line_number));
        CREATE TABLE IF NOT EXISTS cart_checkout_schema.checkout_total_snapshot (
          checkout_total_snapshot_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), checkout_session_id uuid NOT NULL REFERENCES cart_checkout_schema.checkout_session(checkout_session_id) ON DELETE CASCADE,
          currency_code char(3) NOT NULL, sub_total numeric(19,4) NOT NULL, discount_total numeric(19,4) NOT NULL DEFAULT 0,
          shipping_total numeric(19,4) NOT NULL DEFAULT 0, handling_total numeric(19,4) NOT NULL DEFAULT 0, tax_total numeric(19,4) NOT NULL DEFAULT 0,
          grand_total numeric(19,4) NOT NULL, input_hash char(64) NOT NULL, quoted_at timestamptz NOT NULL,
          pricing_version varchar(128), tax_version varchar(128), shipping_version varchar(128), created_at timestamptz NOT NULL DEFAULT current_timestamp,
          CONSTRAINT checkout_total_currency_check CHECK(currency_code ~ '^[A-Z]{3}$'),
          CONSTRAINT checkout_total_nonnegative_check CHECK(sub_total>=0 AND discount_total>=0 AND shipping_total>=0 AND handling_total>=0 AND tax_total>=0 AND grand_total>=0));
        CREATE UNIQUE INDEX IF NOT EXISTS checkout_total_snapshot_session_idx ON cart_checkout_schema.checkout_total_snapshot(checkout_session_id);
        CREATE TABLE IF NOT EXISTS cart_checkout_schema.checkout_submission (
          submission_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), checkout_session_id uuid NOT NULL REFERENCES cart_checkout_schema.checkout_session(checkout_session_id),
          tenant_id varchar(128) NOT NULL, store_id varchar(128) NOT NULL, currency_code char(3) NOT NULL, amount numeric(19,4) NOT NULL,
          payment_module varchar(128) NOT NULL, payment_type varchar(64) NOT NULL, state cart_checkout_schema.submission_state NOT NULL DEFAULT 'PENDING',
          order_reference uuid, payment_reference uuid, inventory_reservation_reference uuid, created_at timestamptz NOT NULL DEFAULT current_timestamp,
          updated_at timestamptz NOT NULL DEFAULT current_timestamp, CONSTRAINT checkout_submission_currency_check CHECK(currency_code ~ '^[A-Z]{3}$'),
          CONSTRAINT checkout_submission_amount_check CHECK(amount>=0));
        CREATE INDEX IF NOT EXISTS checkout_submission_session_idx ON cart_checkout_schema.checkout_submission(checkout_session_id);
        CREATE TABLE IF NOT EXISTS cart_checkout_schema.checkout_idempotency_key (
          idempotency_record_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id varchar(128) NOT NULL, store_id varchar(128) NOT NULL, customer_id bigint,
          cart_id bigint NOT NULL REFERENCES cart_checkout_schema.shopping_cart(cart_id), operation varchar(64) NOT NULL, idempotency_key varchar(255) NOT NULL,
          request_hash char(64) NOT NULL, state cart_checkout_schema.idempotency_state NOT NULL DEFAULT 'IN_PROGRESS', original_status integer,
          original_response jsonb, created_at timestamptz NOT NULL DEFAULT current_timestamp, updated_at timestamptz NOT NULL DEFAULT current_timestamp,
          CONSTRAINT checkout_idempotency_scope_unique UNIQUE(tenant_id,store_id,customer_id,cart_id,operation,idempotency_key));
        CREATE TABLE IF NOT EXISTS cart_checkout_schema.cart_quote_reference (
          quote_reference_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id varchar(128) NOT NULL, store_id varchar(128) NOT NULL,
          checkout_session_id uuid REFERENCES cart_checkout_schema.checkout_session(checkout_session_id), cart_id bigint NOT NULL REFERENCES cart_checkout_schema.shopping_cart(cart_id),
          quote_kind cart_checkout_schema.quote_kind NOT NULL, provider_quote_reference varchar(255) NOT NULL, provider_version varchar(128),
          expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT current_timestamp,
          CONSTRAINT cart_quote_reference_unique UNIQUE(tenant_id,store_id,cart_id,quote_kind,provider_quote_reference));
        CREATE INDEX IF NOT EXISTS cart_quote_reference_active_idx ON cart_checkout_schema.cart_quote_reference(tenant_id,store_id,cart_id,quote_kind,expires_at);
        CREATE TABLE IF NOT EXISTS cart_checkout_schema.ms04_outbox (
          event_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id varchar(128) NOT NULL, store_id varchar(128) NOT NULL, aggregate_id uuid NOT NULL,
          event_type varchar(128) NOT NULL, payload jsonb NOT NULL, state cart_checkout_schema.outbox_state NOT NULL DEFAULT 'PENDING',
          attempt_count integer NOT NULL DEFAULT 0, occurred_at timestamptz NOT NULL DEFAULT current_timestamp, published_at timestamptz,
          correlation_id uuid, CONSTRAINT ms04_outbox_attempt_check CHECK(attempt_count>=0));
        CREATE INDEX IF NOT EXISTS ms04_outbox_publish_idx ON cart_checkout_schema.ms04_outbox(state,occurred_at);
        CREATE TABLE IF NOT EXISTS cart_checkout_schema.ms04_inbox (
          event_id uuid PRIMARY KEY, reservation_id uuid, received_at timestamptz NOT NULL DEFAULT current_timestamp);
        """;

    private const string MigrationSql = """
        ALTER TABLE cart_checkout_schema.shopping_cart ADD COLUMN IF NOT EXISTS correlation_id uuid;
        ALTER TABLE cart_checkout_schema.shopping_cart ADD COLUMN IF NOT EXISTS currency_code char(3) NOT NULL DEFAULT 'CAD';
        ALTER TABLE cart_checkout_schema.shopping_cart_item ADD COLUMN IF NOT EXISTS obsolete boolean NOT NULL DEFAULT false;
        ALTER TABLE cart_checkout_schema.checkout_session ADD COLUMN IF NOT EXISTS failure_code varchar(128);
        ALTER TABLE cart_checkout_schema.checkout_submission ADD COLUMN IF NOT EXISTS inventory_reservation_reference uuid;
        ALTER TABLE cart_checkout_schema.ms04_outbox ADD COLUMN IF NOT EXISTS attempt_count integer NOT NULL DEFAULT 0;
        CREATE UNIQUE INDEX IF NOT EXISTS checkout_idempotency_scope_coalesced_idx
          ON cart_checkout_schema.checkout_idempotency_key(tenant_id,store_id,COALESCE(customer_id,0),cart_id,operation,idempotency_key);
        """;
}
